package com.vladislaviliev.newair.user.location

object SampleLocations {
    val locations = List<UserLocation>(52) { i ->
        val name = when (i) {
            0 -> "Alice"
            1 -> "Aaron"
            2 -> "Bella"
            3 -> "Benjamin"
            4 -> "Chloe"
            5 -> "Caleb"
            6 -> "Diana"
            7 -> "Daniel"
            8 -> "Emily"
            9 -> "Ethan"
            10 -> "Fiona"
            11 -> "Felix"
            12 -> "Grace"
            13 -> "Gabriel"
            14 -> "Hannah"
            15 -> "Henry"
            16 -> "Isabella"
            17 -> "Isaac"
            18 -> "Julia"
            19 -> "Jack"
            20 -> "Katherine"
            21 -> "Kevin"
            22 -> "Lily"
            23 -> "Liam"
            24 -> "Mia"
            25 -> "Mason"
            26 -> "Nora"
            27 -> "Noah"
            28 -> "Olivia"
            29 -> "Owen"
            30 -> "Penelope"
            31 -> "Peter"
            32 -> "Quinn"
            33 -> "Quentin"
            34 -> "Riley"
            35 -> "Ryan"
            36 -> "Sophia"
            37 -> "Samuel"
            38 -> "Taylor"
            39 -> "Thomas"
            40 -> "Uma"
            41 -> "Ulysses"
            42 -> "Victoria"
            43 -> "Vincent"
            44 -> "Willow"
            45 -> "William"
            46 -> "Xenia"
            47 -> "Xavier"
            48 -> "Yara"
            49 -> "Yusuf"
            50 -> "Zoe"
            51 -> "Zachary"
            else -> "Unknown"
        }
        UserLocation(i + 2, name, 0.0, 0.0)
    }
}